version: '3.8'

services:
  carbon:
    build:
      context: .
    networks:
      - protec-api_global
    ports:
      - "8081:8001"
    container_name: carbon-back
    command: "sleep infinity"
    volumes:
      - carbon-static:/app/static
      - carbon-data:/app/data
      - .:/app
    privileged: true
    environment:
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_SETTINGS_MODULE

volumes:
  carbon-data:
  carbon-static:

networks:
  protec-api_global:
    external: true