version: '3.8'

services:
  carbon:
    build:
      context: .
      network: host
    restart: unless-stopped
    container_name: carbon-back
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - carbon-data:/app/data
    environment:
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_SETTINGS_MODULE=settings.prod

volumes:
  carbon-data:
