# Generated by Django 5.0.1 on 2024-01-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("address", models.CharField(max_length=255, verbose_name="adresse")),
                (
                    "zip_code",
                    models.CharField(max_length=255, verbose_name="code postal"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="ville")),
                ("comment", models.TextField(verbose_name="notes")),
            ],
            options={
                "verbose_name": "adresse",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="identifiant")),
                (
                    "type",
                    models.CharField(
                        choices=[], max_length=255, verbose_name="type de véhicule"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=255, verbose_name="Marque et modèle"),
                ),
                (
                    "carburant",
                    models.CharField(
                        choices=[
                            ("DIESEL", "gasoil"),
                            ("UNLEADED_95_10", "SP 95-E10"),
                            ("UNLEADED_98", "SP 98"),
                            ("ETHANOL", "E85"),
                            ("ELECTRIC", "électrique"),
                        ],
                        max_length=255,
                        verbose_name="carburant",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=255, verbose_name="numéro d'immatriculation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "opérationnel"),
                            ("IN_REPAIR", "en réparation"),
                            ("OUT_OF_ORDER", "en panne"),
                        ],
                        default="OPERATIONAL",
                        max_length=255,
                        verbose_name="statut",
                    ),
                ),
                (
                    "parking_location",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.location",
                        verbose_name="emplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "véhicule",
            },
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mécanique", [("engine", "moteur")]),
                            ("éclairage", [("bulb", "ampoule")]),
                        ],
                        max_length=255,
                        verbose_name="type d'anomalie",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "ouvert"),
                            ("SOLVED", "résolu"),
                            ("CANCELLED", "annulé"),
                        ],
                        max_length=255,
                        verbose_name="statut",
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "solution_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de résolution"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.vehicle"
                    ),
                ),
            ],
            options={
                "verbose_name": "anomalie",
            },
        ),
    ]
