# Generated by Django 5.0.1 on 2024-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_vehicle_mileage_trip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="carburant",
            new_name="fuel",
        ),
        migrations.AlterField(
            model_name="defect",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Ouvert"),
                    ("CONFIRMED", "Confirmé"),
                    ("SOLVED", "Résolu"),
                    ("CANCELLED", "Annulé"),
                ],
                default="OPEN",
                max_length=255,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="ending_mileage",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="kilométrage d'arrivée"
            ),
        ),
    ]
