# Generated by Django 5.0.1 on 2024-01-23 18:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_carburant_vehicle_fuel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="date"),
                ),
                ("mileage", models.IntegerField(default=0, verbose_name="kilométrage")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="montant"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="quantité"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.vehicle"
                    ),
                ),
            ],
        ),
    ]
