# Generated by Django 5.0.1 on 2024-05-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_fuelexpense"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fuelexpense",
            options={
                "verbose_name": "Dépense de carburant",
                "verbose_name_plural": "Dépenses de carburant",
            },
        ),
        migrations.AlterField(
            model_name="fuelexpense",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.vehicle",
                verbose_name="véhicule",
            ),
        ),
    ]
