# Generated by Django 5.1.4 on 2025-02-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_location_options_alter_fuelexpense_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="parking_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.location",
                verbose_name="emplacement",
            ),
        ),
    ]
