# Generated by Django 5.0.1 on 2025-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_vehicle_parking_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="inventory",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="inventaire"
            ),
        ),
    ]
