# Generated by Django 5.1.5 on 2025-08-18 21:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_vehicle_parking_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=255, unique=True, verbose_name="clé"),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="valeur"
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètre",
                "verbose_name_plural": "paramètres",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
