# Generated by Django 5.1.5 on 2025-08-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_setting"),
        ("main", "0010_vehicle_inventory"),
    ]

    operations = []
