# Generated by Django 5.1.5 on 2025-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_merge_0010_setting_0010_vehicle_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelexpense",
            name="form_of_payment",
            field=models.CharField(
                choices=[
                    ("FUEL CARD", "Carte carburant"),
                    ("CORPORATE BANK CARD", "Carte bancaire structure"),
                    ("PERSONAL BANK CARD", "Carte bancaire personnelle"),
                ],
                default="FUEL CARD",
                max_length=255,
                verbose_name="Moyen de paiement",
            ),
        ),
    ]
