# Generated by Django 5.2.7 on 2025-10-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_fuelexpense_form_of_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="mileage",
        ),
    ]
