# Generated by Django 5.2.7 on 2026-02-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_vehicle_mileage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defect",
            name="type",
        ),
    ]
