# Generated by Django 5.2.8 on 2026-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_remove_defect_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[("MAJOR", "Majeure"), ("MINOR", "Mineure")],
                max_length=255,
                null=True,
                verbose_name="gravité",
            ),
        ),
    ]
