# Generated by Django 5.2.8 on 2026-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_remove_defect_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_eprotec",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID eprotec du véhicule"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="driver_eprotec",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID eprotec du conducteur"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="event_eprotec",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID eprotec de l'événement"
            ),
        ),
    ]
