# Generated by Django 5.2.14 on 2026-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_defect_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="defects/", verbose_name="photo"
            ),
        ),
    ]
