# Generated by Django 5.2.16 on 2026-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_defect_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="finished",
            field=models.BooleanField(default=False, verbose_name="terminé"),
        ),
    ]
